### ISSUE TITLE
Repositioning of search bar

### ISSUE THREAD

**Issue by terenceneo** [nus-ieee-hkn/nus-ieee-hkn.github.io#19]
Motivation:
- UX improvements to enable quicker access to information
-  Currently, access to search bar requires 2 extra clicks (menu > search) before the query can be typed in

Proposed improvements:
- Shift search bar into header or footer for quick access from any page
- create a button for contact page beside the search bar

**Comment by kstonekuan** [comment]
May want to remove the contact us button found on the index page since it is now near the search bar, maybe shift the description there to the footer as well
